### ISSUE TITLE
Safari 11.0.3 Navigation Closing doesn't work. 

### ISSUE THREAD

**Issue by mittelgrau** [thundergolfer/junior-theme#60]
The Navigation can't be closed, it only prints some 'yes' messages  to the console. Consider using the checkbox hack for your navigation. No Javascript Dependency and good browser support. Maybe check the Apple homepage code or read here : https://css-tricks.com/the-checkbox-hack/

**Comment by thundergolfer** [comment]
Cheers for the heads up. Will look into this.

**Comment by thundergolfer** [comment]
This has been fixed with 42bf5eede36bafb9ccc22fa25724aa99c83036ac. Thanks for pointing out the original issue. 

Tested with `Safari Version 12.0.2 (14606.3.4)` 👍
